### PR TITLE
searchfix/issue8

### PR DESCRIPTION
**Pull request by philwilliammee**
This pull request fixs issue
https://github.com/CU-CommunityApps/cwd_project/issues/2
and addresses issue 
https://github.com/CU-CommunityApps/cwd_base/issues/8

(Also, whitespace tweaks.)

### CODE REVIEW

**Comment by alisonjo315** [comment]
oops, commented on the wrong one -- "looking, thanks!"

**Comment by alisonjo315** [comment]
It looks great!  I want there to be a note "on the record" that there were whitespace tweaks, too, and I just learned that I can update the PR description haha, so I did that :)

Love the "default" in the switch, good thinking.  Question: "project search," I'm not sure that phrase is meaningful, OR maybe it just means something I'm not aware of.  (Oh and, probably add a period at the end of the message, I think......?)
`console.warn($(this).val() + " not found in project search");`

**Comment by alisonjo315** [comment]
(meanwhile)

@philwilliammee The code from project.js works great on the new FCS site!  Aside from the thoughts in my prior comment, it all looks good to me!

**Comment by philwilliammee** [comment]
For the whitespaces I have my IDE set up to use drupal code standards. https://www.drupal.org/docs/develop/standards/javascript/javascript-coding-standards
```txt
All code MUST indent using two (2) space characters,
```
if your using anything outside of the drupal code standards it should be noted in the doc block.

**Pull request merged**
